class MPMConfig(object):
    def __init__(self):
        self.id = 0
        self.n_grid = 128
        self.res = 512
        self.n_particles = 9000
        self.dim = 2
        self.dt = 1e-4 
        self.p_rho = 1
        self.p_vol = (1/self.n_grid * 0.5) **self.dim
        self.E, self.nu = 0.1e4, 0.2  # Young's modulus and Poisson's ratio
        self.la = 100000
        # self.E, self.nu = 0.9e2, 0.2  # Young's modulus and Poisson's ratio
        self.output_folder = None
        self.benchmark_path = None
        self.material = 1
        self.save_end_state = False
        # self.n_timesteps = 4096
        self.n_timesteps = 2048 
        self.quantized_properties = None
        self.n_vec2_vars = 0
        self.n_mat2_vars = 0
        self.use_quantaichi = False
        self.use_hand_scheme = False
        self.use_difftaichi = False
        self.forward_only_mode = False
        self.nlogn_mode = False
        self.pos_output_folder = None
        self.quant_bits = None
        self.quant_ranges = None
        self.use_g2p2g = False
        self.use_sdf_collider = False
        self.use_bls = False
        self.use_bitpack = False
        self.use_fluid = True
        self.use_friction = True
        self.use_dithering = True
        self.use_grad_clip = False
        self.use_height_loss = False
        self.use_bound_clip = False
        self.bound = None
        self.lb = None
        self.ub = None
        self.g = 9.8
        self.steps = 128
        self.use_dithering = True
        self.compute_fp = 'f64'
        self.size = 4.0
        self.task = -1
        self.softer = False
        self.refine_ranges = False
        self.hand_scheme_exp = False
    
